// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package boot

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitHandle() (*Handle, func(), error) {
	service := initMicroService()
	webService := initMicroWebService(service)
	client := initMicroServiceClient(service)
	queryService := initAssistService(service)
	handle := &Handle{
		Web:           webService,
		Micro:         service,
		Client:        client,
		AssistService: queryService,
	}
	return handle, func() {
	}, nil
}

// wire.go:

var baseSet = wire.NewSet(initMicroServiceClient, initAssistService, initMicroService, initMicroWebService)
